# Generated by Django 3.2.13 on 2022-11-10 13:12

from django.conf import settings
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='images/')),
                ('content', models.TextField()),
                ('jjim', models.ManyToManyField(related_name='jjim_product', to=settings.AUTH_USER_MODEL)),
                ('like_uesrs', models.ManyToManyField(related_name='like_product', to=settings.AUTH_USER_MODEL)),
                ('review', models.ManyToManyField(related_name='review_product', to='reviews.Review')),
            ],
        ),
    ]
