# Generated by Django 3.2.13 on 2022-11-11 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='like_uesrs',
            new_name='like_users',
        ),
    ]
