# Generated by Django 3.2.13 on 2022-11-13 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='like_users',
        ),
    ]
